In [ ]:
firstname='i am santhirarajah sivasthigan'.split()[-1]
lastname='i am santhirarajah sivasthigan'.split()[2]

In [ ]:
print(firstname)
print(lastname)

sivasthigan
santhirarajah


In [ ]:
nickname='sivasthigan'

In [ ]:
print(nickname[0:-3])

sivasthi


In [ ]:
x={'apple':10,'orange':30,'pineapple':89}
print(x)

{'apple': 10, 'orange': 30, 'pineapple': 89}


In [ ]:
x['apple']

10

In [ ]:
x['orange']

30

In [ ]:
for i in x:
  print(x[i])

10
30
89


In [ ]:
sr={'name':'sivasthi','no':10, 'by':'bicycle'}
x='{} bought {}kg of rice by riding with {}'
y=x.format(sr['name'],sr['no'],sr['by'])
print(y)

sivasthi bought 10kg of rice by riding with bicycle


In [ ]:
import pandas as pd


In [ ]:
r=pd.read_csv('/content/drive/MyDrive/people-example.csv')
r

First Name Last Name        Country  age
0        Bob     Smith  United States   24
1      Alice  Williams         Canada   23
2    Malcolm      Jone        England   22
3      Felix     Brown            USA   23
4       Alex    Cooper         Poland   23
5        Tod  Campbell  United States   22
6      Derek      Ward    Switzerland   25

In [ ]:
with open('/content/drive/MyDrive/people-example.csv') as csvfile:
    msg=list(csv.DictReader(csvfile))

In [ ]:
msg[:3]

[OrderedDict([('First Name', 'Bob'),
              ('Last Name', 'Smith'),
              ('Country', 'United States'),
              ('age', '24')]),
 OrderedDict([('First Name', 'Alice'),
              ('Last Name', 'Williams'),
              ('Country', 'Canada'),
              ('age', '23')]),
 OrderedDict([('First Name', 'Malcolm'),
              ('Last Name', 'Jone'),
              ('Country', 'England'),
              ('age', '22')])]

In [ ]:
msg[1]

OrderedDict([('First Name', 'Alice'),
             ('Last Name', 'Williams'),
             ('Country', 'Canada'),
             ('age', '23')])

In [ ]:
msg[0].keys()

odict_keys(['First Name', 'Last Name', 'Country', 'age'])

In [ ]:
msg[0].values()

odict_values(['Bob', 'Smith', 'United States', '24'])

In [ ]:
msg[1]['First Name']

'Alice'

In [ ]:
len(msg)

7

In [ ]:
for i in range(len(msg)):
  print(msg[i]['First Name'])

Bob
Alice
Malcolm
Felix
Alex
Tod
Derek


In [ ]:
for i in msg:
  print(i)
  

OrderedDict([('First Name', 'Bob'), ('Last Name', 'Smith'), ('Country', 'United States'), ('age', '24')])
OrderedDict([('First Name', 'Alice'), ('Last Name', 'Williams'), ('Country', 'Canada'), ('age', '23')])
OrderedDict([('First Name', 'Malcolm'), ('Last Name', 'Jone'), ('Country', 'England'), ('age', '22')])
OrderedDict([('First Name', 'Felix'), ('Last Name', 'Brown'), ('Country', 'USA'), ('age', '23')])
OrderedDict([('First Name', 'Alex'), ('Last Name', 'Cooper'), ('Country', 'Poland'), ('age', '23')])
OrderedDict([('First Name', 'Tod'), ('Last Name', 'Campbell'), ('Country', 'United States'), ('age', '22')])
OrderedDict([('First Name', 'Derek'), ('Last Name', 'Ward'), ('Country', 'Switzerland'), ('age', '25')])


In [ ]:
name=set(d['First Name'] for d in msg)
name

{'Alex', 'Alice', 'Bob', 'Derek', 'Felix', 'Malcolm', 'Tod'}

In [ ]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']
print(people[0].split()[1])
for i in people:
    k=i.split()[0]+i.split()[-1]
    print(k)

def split_title_and_name(person):
        j=0
        t=people[j].split()[0]+people[j].split()[-1]
        j=j+1
        return t
     
list(map(split_title_and_name,people))

Christopher
Dr.Brooks
Dr.Collins-Thompson
Dr.Vydiswaran
Dr.Romero


['Dr.Brooks', 'Dr.Brooks', 'Dr.Brooks', 'Dr.Brooks']

In [ ]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']
for i in people:
   def split_title_and_name(person):
        
      return person.split()[0]+person.split()[-1]
        
list(map(split_title_and_name,people))

['Dr.Brooks', 'Dr.Collins-Thompson', 'Dr.Vydiswaran', 'Dr.Romero']

In [ ]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

#def split_title_and_name(person):
 #   return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    #print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))
    y=lambda x: x.split()[0] + ' ' + x.split()[-1]
    print(y(person))
#option 2
#list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

Dr. Brooks
Dr. Collins-Thompson
Dr. Vydiswaran
Dr. Romero


In [ ]:
y=[]
for i in range(0,10):
  if i%2==0:
    y.append(i)
    print(i)

[0, 2, 4, 6, 8]


In [ ]:
x=[i for i in range(0,10) if i%2==0]
print(x)

[0, 2, 4, 6, 8]


In [ ]:
x=[i for i in range(10)]
print(x)
t=[i*2 for i in range (10)]
print(t)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [i*j for i in range(10) for j in range(10) ]


True

# Array creation

In [ ]:
import numpy as np
import math
#arrays are displayed as list or list of list and can be created through list as well

In [ ]:
a=np.array([1,2,3,4])
b=[1,2,3,4]
print(a)
print(b)
#print no of dimensions of array
print(a.ndim)

[1 2 3 4]
[1, 2, 3, 4]
1


In [ ]:
#creating multi dimensional array
c=np.array([[1,2,3],[4,5,6]])
print(c)
c.shape#print the length of each dimension in tuple

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
np.random.rand(2,3)

array([[0.72231178, 0.95176802, 0.47658979],
       [0.5929817 , 0.77329374, 0.77567007]])

In [ ]:
#create an array from 10 to 50
f=np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Array operations

In [ ]:
a=np.array([10,9,8,7])
b=np.array([1,2,3,4])

In [ ]:
a-b
a+b*2

array([12, 13, 14, 15])