In [ ]:
import pandas as pd
import numpy as np
import sklearn 
from sklearn.model_selection import train_test_split


In [ ]:
products=pd.read_csv('/content/drive/MyDrive/amazon_baby.csv')
products

name  ... rating
0                                Planetwise Flannel Wipes  ...      3
1                                   Planetwise Wipe Pouch  ...      5
2                     Annas Dream Full Quilt with 2 Shams  ...      5
3       Stop Pacifier Sucking without tears with Thumb...  ...      5
4       Stop Pacifier Sucking without tears with Thumb...  ...      5
...                                                   ...  ...    ...
183526  Baby Teething Necklace for Mom Pretty Donut Sh...  ...      5
183527  Baby Teething Necklace for Mom Pretty Donut Sh...  ...      5
183528   Abstract 2 PK Baby / Toddler Training Cup (Pink)  ...      5
183529  Baby Food Freezer Tray - Bacteria Resistant, B...  ...      5
183530  Best 2 Pack Baby Car Shade for Kids - Window S...  ...      5

[183531 rows x 3 columns]

In [ ]:
products = products.fillna({'review':''})

In [ ]:
products

name  ... rating
0                                Planetwise Flannel Wipes  ...      3
1                                   Planetwise Wipe Pouch  ...      5
2                     Annas Dream Full Quilt with 2 Shams  ...      5
3       Stop Pacifier Sucking without tears with Thumb...  ...      5
4       Stop Pacifier Sucking without tears with Thumb...  ...      5
...                                                   ...  ...    ...
183526  Baby Teething Necklace for Mom Pretty Donut Sh...  ...      5
183527  Baby Teething Necklace for Mom Pretty Donut Sh...  ...      5
183528   Abstract 2 PK Baby / Toddler Training Cup (Pink)  ...      5
183529  Baby Food Freezer Tray - Bacteria Resistant, B...  ...      5
183530  Best 2 Pack Baby Car Shade for Kids - Window S...  ...      5

[183531 rows x 3 columns]

In [ ]:
def remove_punctuation(s):  
  import string
  translator = str.maketrans('', '', string.punctuation)
  return s.translate(translator)

In [ ]:
products['review_clean'] = products['review'].apply(remove_punctuation)

In [ ]:
products

name  ...                                       review_clean
0                                Planetwise Flannel Wipes  ...  These flannel wipes are OK but in my opinion n...
1                                   Planetwise Wipe Pouch  ...  it came early and was not disappointed i love ...
2                     Annas Dream Full Quilt with 2 Shams  ...  Very soft and comfortable and warmer than it l...
3       Stop Pacifier Sucking without tears with Thumb...  ...  This is a product well worth the purchase  I h...
4       Stop Pacifier Sucking without tears with Thumb...  ...  All of my kids have cried nonstop when I tried...
...                                                   ...  ...                                                ...
183526  Baby Teething Necklace for Mom Pretty Donut Sh...  ...  Such a great idea very handy to have and look ...
183527  Baby Teething Necklace for Mom Pretty Donut Sh...  ...  This product rocks  It is a great blend of fun...
183528   Abstract 2 PK Baby / Toddler Training Cup (Pink)  ...  This item looks great and cool for my kidsI kn...
183529  Baby Food Freezer Tray - Bacteria Resistant, B...  ...  I am extremely happy with this product I have ...
183530  Best 2 Pack Baby Car Shade for Kids - Window S...  ...  I love this product very mush  I have bought m...

[183531 rows x 4 columns]

In [ ]:
products=products[products['rating']!=3]

In [ ]:
products

name  ...                                       review_clean
1                                   Planetwise Wipe Pouch  ...  it came early and was not disappointed i love ...
2                     Annas Dream Full Quilt with 2 Shams  ...  Very soft and comfortable and warmer than it l...
3       Stop Pacifier Sucking without tears with Thumb...  ...  This is a product well worth the purchase  I h...
4       Stop Pacifier Sucking without tears with Thumb...  ...  All of my kids have cried nonstop when I tried...
5       Stop Pacifier Sucking without tears with Thumb...  ...  When the Binky Fairy came to our house we didn...
...                                                   ...  ...                                                ...
183526  Baby Teething Necklace for Mom Pretty Donut Sh...  ...  Such a great idea very handy to have and look ...
183527  Baby Teething Necklace for Mom Pretty Donut Sh...  ...  This product rocks  It is a great blend of fun...
183528   Abstract 2 PK Baby / Toddler Training Cup (Pink)  ...  This item looks great and cool for my kidsI kn...
183529  Baby Food Freezer Tray - Bacteria Resistant, B...  ...  I am extremely happy with this product I have ...
183530  Best 2 Pack Baby Car Shade for Kids - Window S...  ...  I love this product very mush  I have bought m...

[166752 rows x 4 columns]

In [ ]:
products['sentiment']=products['rating'].apply(lambda rating:+1 if rating>3 else -1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
products

name  ... sentiment
1                                   Planetwise Wipe Pouch  ...         1
2                     Annas Dream Full Quilt with 2 Shams  ...         1
3       Stop Pacifier Sucking without tears with Thumb...  ...         1
4       Stop Pacifier Sucking without tears with Thumb...  ...         1
5       Stop Pacifier Sucking without tears with Thumb...  ...         1
...                                                   ...  ...       ...
183526  Baby Teething Necklace for Mom Pretty Donut Sh...  ...         1
183527  Baby Teething Necklace for Mom Pretty Donut Sh...  ...         1
183528   Abstract 2 PK Baby / Toddler Training Cup (Pink)  ...         1
183529  Baby Food Freezer Tray - Bacteria Resistant, B...  ...         1
183530  Best 2 Pack Baby Car Shade for Kids - Window S...  ...         1

[166752 rows x 5 columns]

In [ ]:
import json
with open('/content/drive/MyDrive/sentimentpred/module-2-assignment-test-idx.json') as test_data_file:    
    test_data_idx = json.load(test_data_file)
with open('/content/drive/MyDrive/sentimentpred/module-2-assignment-train-idx.json') as train_data_file:    
    train_data_idx = json.load(train_data_file)

print (train_data_idx[:3])
print (test_data_idx[:3])

[0, 1, 2]
[8, 9, 14]


In [ ]:
train_data=products.iloc[train_data_idx]

In [ ]:
train_data.head()

name  ... sentiment
1                              Planetwise Wipe Pouch  ...         1
2                Annas Dream Full Quilt with 2 Shams  ...         1
3  Stop Pacifier Sucking without tears with Thumb...  ...         1
4  Stop Pacifier Sucking without tears with Thumb...  ...         1
5  Stop Pacifier Sucking without tears with Thumb...  ...         1

[5 rows x 5 columns]

In [ ]:
test_data = products.iloc[test_data_idx]
test_data.head()


name  ... sentiment
9   Baby Tracker&reg; - Daily Childcare Journal, S...  ...         1
10  Baby Tracker&reg; - Daily Childcare Journal, S...  ...         1
16     Nature's Lullabies First Year Sticker Calendar  ...         1
20    Nature's Lullabies Second Year Sticker Calendar  ...         1
28                        Lamaze Peekaboo, I Love You  ...         1

[5 rows x 5 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(token_pattern=r'\b\w+\b')
     # Use this token pattern to keep single-letter words
# First, learn vocabulary from the training data and assign columns to words
# Then convert the training data into a sparse matrix
train_matrix = vectorizer.fit_transform(train_data['review_clean'])
# Second, convert the test data into a sparse matrix, using the same word-column mapping
test_matrix = vectorizer.transform(test_data['review_clean'])

In [ ]:
from sklearn.linear_model import LogisticRegression
sentiment_model = LogisticRegression()
sentiment_model.fit(train_matrix, train_data['sentiment'])

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
np.sum(sentiment_model.coef_ >= 0)


90360

In [ ]:
sample_test_data=test_data.iloc[10:13]

In [ ]:
sample_test_data

name  ... sentiment
59                          Our Baby Girl Memory Book  ...         1
71  Wall Decor Removable Decal Sticker - Colorful ...  ...        -1
91  New Style Trailing Cherry Blossom Tree Decal R...  ...        -1

[3 rows x 5 columns]

In [ ]:
sample_test_matrix=vectorizer.transform(sample_test_data['review_clean'])


In [ ]:
sentiment_model.predict(sample_test_matrix)

array([ 1, -1, -1])

In [ ]:
sentiment_model.decision_function(sample_test_matrix)

array([  4.8951336 ,  -3.20137131, -10.15834422])

In [ ]:
test_scores=sentiment_model.decision_function(test_matrix)
test_scores

array([ 2.26883388, 14.70276475,  2.82367937, ..., 10.28124528,
       11.0317498 ,  4.46838428])

In [ ]:
positive_idx = np.argsort(-test_scores)[:20]
positive_idx


array([18112, 15732, 21531, 25554, 24286, 30634,  9555, 24899, 32782,
       20743,  2570, 30535, 30297, 26830,  9125, 14482, 26838, 33060,
       17558, 31224])

In [ ]:
print (test_scores[positive_idx[0]])


46.08255976109098


In [ ]:
test_data.iloc[positive_idx]


name  ... sentiment
100166  Infantino Wrap and Tie Baby Carrier, Black Blu...  ...         1
87017     Baby Einstein Around The World Discovery Center  ...         1
119182  Roan Rocco Classic Pram Stroller 2-in-1 with B...  ...         1
140816         Diono RadianRXT Convertible Car Seat, Plum  ...         1
133651                  Britax 2012 B-Agile Stroller, Red  ...         1
168697  Graco FastAction Fold Jogger Click Connect Str...  ...         1
52631   Evenflo X Sport Plus Convenience Stroller - Ch...  ...         1
137034         Graco Pack 'n Play Element Playard - Flint  ...         1
180646      Mamas &amp; Papas 2014 Urbo2 Stroller - Black  ...         1
114796  Fisher-Price Cradle 'N Swing,  My Little Snuga...  ...         1
14008       Stork Craft Beatrice Combo Tower Chest, White  ...         1
168081  Buttons Cloth Diaper Cover - One Size - 8 Colo...  ...         1
166827  Britax Boulevard 70-G3 Convertible Car Seat Se...  ...         1
147949  Baby Jogger City Mini GT Single Stroller, Shad...  ...         1
50315          P'Kolino Silly Soft Seating in Tias, Green  ...         1
80155   Simple Wishes Hands-Free Breastpump Bra, Pink,...  ...         1
147996  Baby Jogger City Mini GT Double Stroller, Shad...  ...         1
182089  Summer Infant Wide View Digital Color Video Mo...  ...         1
97325   Freemie Hands-Free Concealable Breast Pump Col...  ...         1
172085                Stokke Scoot Stroller - Light Green  ...         1

[20 rows x 5 columns]

In [ ]:
negative_idx = np.argsort(test_scores)[:20]
print(negative_idx)
print(test_scores[negative_idx[0]])
test_data.iloc[negative_idx]

[17069  2931 28184 21700  8818 17222  9655 31928 14711 30373 17034 10814
 13752  5831 13939 17428 13751  1942   205 20594]
-31.994102893551005


name  ... sentiment
94560   The First Years True Choice P400 Premium Digit...  ...        -1
16042         Fisher-Price Ocean Wonders Aquarium Bouncer  ...        -1
155287  VTech Communications Safe &amp; Sounds Full Co...  ...        -1
120209  Levana Safe N'See Digital Video Baby Monitor w...  ...        -1
48694   Adiri BPA Free Natural Nurser Ultimate Bottle ...  ...        -1
95420        One Step Ahead Hide-Away Extra Long Bed Rail  ...        -1
53207                 Safety 1st High-Def Digital Monitor  ...        -1
176046       Baby Trend Inertia Infant Car Seat - Horizon  ...        -1
81332               Cloth Diaper Sprayer--styles may vary  ...        -1
167249  Samsung SEW-3037W Wireless Pan Tilt Video Baby...  ...        -1
94389                Snuza Portable Baby Movement Monitor  ...        -1
59546              Ellaroo Mei Tai Baby Carrier - Hershey  ...        -1
76000          Peg-Perego Tatamia High Chair, White Latte  ...        -1
31741              Regalo My Cot Portable Bed, Royal Blue  ...        -1
77072      Safety 1st Exchangeable Tip 3 in 1 Thermometer  ...        -1
96572    Baby Jogger Summit XC Double Stroller, Red/Black  ...        -1
75994          Peg-Perego Tatamia High Chair, White Latte  ...        -1
10677                   Philips AVENT Newborn Starter Set  ...        -1
1116                Safety 1st Deluxe 4-in-1 Bath Station  ...        -1
113995  Motorola Digital Video Baby Monitor with Room ...  ...        -1

[20 rows x 5 columns]

In [ ]:
test_predicted_y = sentiment_model.predict(test_matrix)
correct_num = np.sum(test_predicted_y == test_data['sentiment'])
total_num = len(test_data['sentiment'])
print ("correct_num: {}, total_num: {}".format(correct_num, total_num))
test_accuracy = correct_num / total_num
print("sentiment_model test accuracy: {}".format(test_accuracy))



correct_num: 31076, total_num: 33336
sentiment_model test accuracy: 0.9322054235661147


In [ ]:
significant_words = ['love', 'great', 'easy', 'old', 'little', 'perfect', 'loves', 
      'well', 'able', 'car', 'broke', 'less', 'even', 'waste', 'disappointed', 
      'work', 'product', 'money', 'would', 'return']

In [ ]:
vectorizer_word_subset = CountVectorizer(vocabulary=significant_words) # limit to 20 words
train_matrix_word_subset = vectorizer_word_subset.fit_transform(train_data['review_clean'])
test_matrix_word_subset = vectorizer_word_subset.transform(test_data['review_clean'])

In [ ]:
simple_model = LogisticRegression()
simple_model.fit(train_matrix_word_subset, train_data['sentiment'])


LogisticRegression()

In [ ]:
simple_model_coef_table = pd.DataFrame({'word':significant_words,'coefficient':simple_model.coef_.flatten()})
simple_model_coef_table.sort_values(['coefficient'], ascending=False)


word  coefficient
6          loves     1.673269
5        perfect     1.510263
0           love     1.363697
2           easy     1.192219
1          great     0.943950
4         little     0.520174
7           well     0.503760
8           able     0.190937
3            old     0.085424
9            car     0.058813
11          less    -0.209348
16       product    -0.320491
18         would    -0.362157
12          even    -0.511456
15          work    -0.621307
17         money    -0.898062
10         broke    -1.652144
13         waste    -2.034489
19        return    -2.109815
14  disappointed    -2.348478

In [ ]:
len(simple_model_coef_table[simple_model_coef_table['coefficient']>0])


10

In [ ]:
test_predicted_y = sentiment_model.predict(test_matrix)
correct_num = np.sum(test_predicted_y == test_data['sentiment'])
total_num = len(test_data['sentiment'])
print ("correct_num: {}, total_num: {}".format(correct_num, total_num))
test_accuracy = correct_num / total_num
print("sentiment_model test accuracy: {}".format(test_accuracy))

test_predicted_y = simple_model.predict(test_matrix_word_subset)
correct_num = np.sum(test_predicted_y == test_data['sentiment'])
total_num = len(test_data['sentiment'])
print ("correct_num: {}, total_num: {}".format(correct_num, total_num))
test_accuracy = correct_num * 1./ total_num
print ("simple_model test accuracy: {}".format(test_accuracy))

correct_num: 31076, total_num: 33336
sentiment_model test accuracy: 0.9322054235661147
correct_num: 28981, total_num: 33336
simple_model test accuracy: 0.8693604511639069


In [ ]:
train_predicted_y = sentiment_model.predict(train_matrix)
correct_num = np.sum(train_predicted_y == train_data['sentiment'])
total_num = len(train_data['sentiment'])
print ("correct_num: {}, total_num: {}".format(correct_num, total_num))
train_accuracy = correct_num * 1./ total_num
print ("sentiment_model training accuracy: {}".format(train_accuracy))

train_predicted_y = simple_model.predict(train_matrix_word_subset)
correct_num = np.sum(train_predicted_y == train_data['sentiment'])
total_num = len(train_data['sentiment'])
print ("correct_num: {}, total_num: {}".format(correct_num, total_num))
train_accuracy = correct_num * 1./ total_num
print ("simple_model training accuracy: {}".format(train_accuracy))

correct_num: 126448, total_num: 133416
sentiment_model training accuracy: 0.9477723811237033
correct_num: 115648, total_num: 133416
simple_model training accuracy: 0.8668225700065959


In [ ]:
positive_label = len(test_data[test_data['sentiment']>0])
negative_label = len(test_data[test_data['sentiment']<0])
print( "positive_label is {}, negative_label is {}".format(positive_label, negative_label))

positive_label is 28095, negative_label is 5241


In [ ]:
baseline_accuracy = positive_label*1./(positive_label+negative_label)
print ("baseline_accuracy is {}".format(baseline_accuracy))


baseline_accuracy is 0.8427825773938085
