In [1]:
import pandas as pd
import numpy as np

In [2]:
products = pd.read_csv('/Users/April/Downloads/amazon_baby.csv')

In [3]:
products.head()

name  \
0                           Planetwise Flannel Wipes   
1                              Planetwise Wipe Pouch   
2                Annas Dream Full Quilt with 2 Shams   
3  Stop Pacifier Sucking without tears with Thumb...   
4  Stop Pacifier Sucking without tears with Thumb...   

                                              review  rating  
0  These flannel wipes are OK, but in my opinion ...       3  
1  it came early and was not disappointed. i love...       5  
2  Very soft and comfortable and warmer than it l...       5  
3  This is a product well worth the purchase.  I ...       5  
4  All of my kids have cried non-stop when I trie...       5

#Perform text cleaning

In [4]:
def remove_punctuation(text):
    import string
    return text.translate(None, string.punctuation) 

In [5]:
products = products.fillna({'review':''})  # fill in N/A's in the review column

In [6]:
products['review_clean'] = products['review'].apply(remove_punctuation)

#Extract Sentiments

We will ignore all reviews with rating = 3, since they tend to have a neutral sentiment.

In [7]:
products = products[products['rating'] != 3]

In [8]:
products['sentiment'] = products['rating'].apply(lambda rating : +1 if rating > 3 else -1)

In [9]:
products.head()

name  \
1                              Planetwise Wipe Pouch   
2                Annas Dream Full Quilt with 2 Shams   
3  Stop Pacifier Sucking without tears with Thumb...   
4  Stop Pacifier Sucking without tears with Thumb...   
5  Stop Pacifier Sucking without tears with Thumb...   

                                              review  rating  \
1  it came early and was not disappointed. i love...       5   
2  Very soft and comfortable and warmer than it l...       5   
3  This is a product well worth the purchase.  I ...       5   
4  All of my kids have cried non-stop when I trie...       5   
5  When the Binky Fairy came to our house, we did...       5   

                                        review_clean  sentiment  
1  it came early and was not disappointed i love ...          1  
2  Very soft and comfortable and warmer than it l...          1  
3  This is a product well worth the purchase  I h...          1  
4  All of my kids have cried nonstop when I tried...          1  
5  When the Binky Fairy came to our house we didn...          1

#Split into training and test sets

In [10]:
train_indice = open('/Users/April/Documents/train_indice.txt','r')

In [11]:
for line in train_indice:
    train_list = [int(x.strip()) for x in line.split(',')]

In [12]:
train_data = products.iloc[train_list]

In [13]:
test_indice = open('/Users/April/Documents/test_indice.txt','r')

In [14]:
for line in test_indice:
    test_list = [int(x.strip()) for x in line.split(',')]

In [15]:
test_data = products.iloc[test_list]

#Build the word count vector for each review

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(token_pattern=r'\b\w+\b')
     # Use this token pattern to keep single-letter words
# First, learn vocabulary from the training data and assign columns to words
# Then convert the training data into a sparse matrix
train_matrix = vectorizer.fit_transform(train_data['review_clean'])
# Second, convert the test data into a sparse matrix, using the same word-column mapping
test_matrix = vectorizer.transform(test_data['review_clean'])

#Train a sentiment classifier with logistic regression

In [17]:
from sklearn import datasets, linear_model
from sklearn.linear_model import LogisticRegression

In [18]:
sentiment_model = LogisticRegression()

In [19]:
sentiment_model.fit(train_matrix, train_data['sentiment'])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0)

In [20]:
sentiment_model.coef_

array([[ -1.24007873e+00,   2.77457341e-05,   2.75413164e-02, ...,
          1.26117918e-02,   2.70404667e-03,  -4.13269084e-05]])

In [21]:
print np.sum(sum(sentiment_model.coef_ >= 0))

87059


# Making predictions with logistic regression

In [22]:
sample_test_data = test_data[10:13]
print sample_test_data

                                                 name  \
59                          Our Baby Girl Memory Book   
71  Wall Decor Removable Decal Sticker - Colorful ...   
91  New Style Trailing Cherry Blossom Tree Decal R...   

                                               review  rating  \
59  Absolutely love it and all of the Scripture in...       5   
71  Would not purchase again or recommend. The dec...       2   
91  Was so excited to get this product for my baby...       1   

                                         review_clean  sentiment  
59  Absolutely love it and all of the Scripture in...          1  
71  Would not purchase again or recommend The deca...         -1  
91  Was so excited to get this product for my baby...         -1  


In [23]:
sample_test_data.iloc[0]['review']

'Absolutely love it and all of the Scripture in it.  I purchased the Baby Boy version for my grandson when he was born and my daughter-in-law was thrilled to receive the same book again.'

In [24]:
sample_test_data.iloc[1]['review']

'Would not purchase again or recommend. The decals were thick almost plastic like and were coming off the wall as I was applying them! The would NOT stick! Literally stayed stuck for about 5 minutes then started peeling off.'

In [25]:
sample_test_matrix = vectorizer.transform(sample_test_data['review_clean'])
scores = sentiment_model.decision_function(sample_test_matrix)
print scores

[  5.60150644  -3.17110494 -10.42378277]


#Prediciting Sentiment

In [26]:
sentiment_model.predict(sample_test_matrix)

array([ 1, -1, -1])

#Probability Predictions

In [27]:
probability = 1/(1+np.exp(-scores))

In [28]:
probability

array([  9.96321286e-01,   4.02676921e-02,   2.97163701e-05])

#Find the most positive (and negative) review

In [29]:
test_matrix = vectorizer.transform(test_data['review_clean'])
scores_test = sentiment_model.decision_function(test_matrix)
predictions = 1/(1+np.exp(-scores_test))

In [30]:
test_data['predictions'] = predictions

/Users/April/anaconda/envs/dato-env/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [31]:
test_data.sort('predictions', ascending = False).iloc[0:20]

name  \
168697  Graco FastAction Fold Jogger Click Connect Str...   
66059        Evenflo 6 Pack Classic Glass Bottle, 4-Ounce   
119182  Roan Rocco Classic Pram Stroller 2-in-1 with B...   
168081  Buttons Cloth Diaper Cover - One Size - 8 Colo...   
80155   Simple Wishes Hands-Free Breastpump Bra, Pink,...   
52631   Evenflo X Sport Plus Convenience Stroller - Ch...   
133651                  Britax 2012 B-Agile Stroller, Red   
137034         Graco Pack 'n Play Element Playard - Flint   
22586      Britax Decathlon Convertible Car Seat, Tiffany   
100166  Infantino Wrap and Tie Baby Carrier, Black Blu...   
87017     Baby Einstein Around The World Discovery Center   
140816         Diono RadianRXT Convertible Car Seat, Plum   
114796  Fisher-Price Cradle 'N Swing,  My Little Snuga...   
97325   Freemie Hands-Free Concealable Breast Pump Col...   
147949  Baby Jogger City Mini GT Single Stroller, Shad...   
180646      Mamas &amp; Papas 2014 Urbo2 Stroller - Black   
50315          P'Kolino Silly Soft Seating in Tias, Green   
165593  Ikea 36 Pcs Kalas Kids Plastic BPA Free Flatwa...   
182089  Summer Infant Wide View Digital Color Video Mo...   
172351  Phil &amp; Teds Navigator Buggy Golden Kiwi Fr...   

                                                   review  rating  \
168697  Graco's FastAction Jogging Stroller definitely...       5   
66059   It's always fun to write a review on those pro...       5   
119182  Great Pram Rocco!!!!!!I bought this pram from ...       5   
168081  We are big Best Bottoms fans here, but I wante...       4   
80155   I just tried this hands free breastpump bra, a...       5   
52631   After seeing this in Parent's Magazine and rea...       5   
133651  [I got this stroller for my daughter prior to ...       4   
137034  My husband and I assembled this Pack n' Play l...       4   
22586   I researched a few different seats to put in o...       4   
100166  I bought this carrier when my daughter was abo...       5   
87017   I am so HAPPY I brought this item for my 7 mon...       5   
140816  I bought this seat for my tall (38in) and thin...       5   
114796  My husband and I cannot state enough how much ...       5   
97325   I absolutely love this product.  I work as a C...       5   
147949  Amazing, Love, Love, Love it !!! All 5 STARS a...       5   
180646  After much research I purchased an Urbo2. It's...       4   
50315   I've purchased both the P'Kolino Little Reader...       4   
165593  For the price this set is unbelievable- and tr...       5   
182089  I love this baby monitor.  I can compare this ...       5   
172351  I'm pretty happy with this stroller. I use it ...       4   

                                             review_clean  sentiment  \
168697  Gracos FastAction Jogging Stroller definitely ...          1   
66059   Its always fun to write a review on those prod...          1   
119182  Great Pram RoccoI bought this pram from Europe...          1   
168081  We are big Best Bottoms fans here but I wanted...          1   
80155   I just tried this hands free breastpump bra an...          1   
52631   After seeing this in Parents Magazine and read...          1   
133651  I got this stroller for my daughter prior to t...          1   
137034  My husband and I assembled this Pack n Play la...          1   
22586   I researched a few different seats to put in o...          1   
100166  I bought this carrier when my daughter was abo...          1   
87017   I am so HAPPY I brought this item for my 7 mon...          1   
140816  I bought this seat for my tall 38in and thin 2...          1   
114796  My husband and I cannot state enough how much ...          1   
97325   I absolutely love this product  I work as a Cu...          1   
147949  Amazing Love Love Love it  All 5 STARS all the...          1   
180646  After much research I purchased an Urbo2 Its e...          1   
50315   Ive purchased both the PKolino Little Reader C...          1   
165593  For the price thi

In [32]:
test_data.sort('predictions', ascending = True).iloc[0:20]

name  \
16042         Fisher-Price Ocean Wonders Aquarium Bouncer   
120209  Levana Safe N'See Digital Video Baby Monitor w...   
77072      Safety 1st Exchangeable Tip 3 in 1 Thermometer   
48694   Adiri BPA Free Natural Nurser Ultimate Bottle ...   
155287  VTech Communications Safe &amp; Sounds Full Co...   
94560   The First Years True Choice P400 Premium Digit...   
53207                 Safety 1st High-Def Digital Monitor   
81332               Cloth Diaper Sprayer--styles may vary   
10677                   Philips AVENT Newborn Starter Set   
113995  Motorola Digital Video Baby Monitor with Room ...   
59546              Ellaroo Mei Tai Baby Carrier - Hershey   
9915         Cosco Alpha Omega Elite Convertible Car Seat   
40079   Chicco Cortina KeyFit 30 Travel System in Adve...   
172090  Belkin WeMo Wi-Fi Baby Monitor for Apple iPhon...   
75994          Peg-Perego Tatamia High Chair, White Latte   
149987                   NUK Cook-n-Blend Baby Food Maker   
154878  VTech Communications Safe &amp; Sound Digital ...   
1116                Safety 1st Deluxe 4-in-1 Bath Station   
31741              Regalo My Cot Portable Bed, Royal Blue   
83234       Thirsties Hemp Inserts 2 Pack, Small 6-18 Lbs   

                                                   review  rating  \
16042   We have not had ANY luck with Fisher-Price pro...       2   
120209  This is the first review I have ever written o...       1   
77072   I thought it sounded great to have different t...       1   
48694   I will try to write an objective review of the...       2   
155287  This is my second video monitoring system, the...       1   
94560   Note: we never installed batteries in these un...       1   
53207   We bought this baby monitor to replace a diffe...       1   
81332   I bought this sprayer out of desperation durin...       1   
10677   It's 3am in the morning and needless to say, t...       1   
113995  DO NOT BUY THIS BABY MONITOR!I purchased this ...       1   
59546   This is basically an overpriced piece of fabri...       1   
9915    I bought this car seat after both seeing  the ...       1   
40079   My wife and I have used this system in two car...       1   
172090  I read so many reviews saying the Belkin WiFi ...       2   
75994   I can see why there are so many good reviews o...       2   
149987  It thought this would be great. I did a lot of...       1   
154878  First, the distance on these are no more than ...       1   
1116    This item is junk.  I originally chose it beca...       1   
31741   If I could give this product zero stars I woul...       1   
83234   My Experience: Babykicks Inserts failure vs RA...       5   

                                             review_clean  sentiment  \
16042   We have not had ANY luck with FisherPrice prod...         -1   
120209  This is the first review I have ever written o...         -1   
77072   I thought it sounded great to have different t...         -1   
48694   I will try to write an objective review of the...         -1   
155287  This is my second video monitoring system the ...         -1   
94560   Note we never installed batteries in these uni...         -1   
53207   We bought this baby monitor to replace a diffe...         -1   
81332   I bought this sprayer out of desperation durin...         -1   
10677   Its 3am in the morning and needless to say thi...         -1   
113995  DO NOT BUY THIS BABY MONITORI purchased this m...         -1   
59546   This is basically an overpriced piece of fabri...         -1   
9915    I bought this car seat after both seeing  the ...         -1   
40079   My wife and I have used this system in two car...         -1   
172090  I read so many reviews saying the Belkin WiFi ...         -1   
75994   I can see why there are so many good reviews o...         -1   
149987  It thought this would be great I did a lot of ...         -1   
154878  First the distance on these are no more than 7...         -1   
1116    This item is junk

#Compute accuracy of the classifier

In [33]:
predicted_sentiment = sentiment_model.predict(test_matrix)

In [34]:
test_data['predicted_sentiment'] = predicted_sentiment

/Users/April/anaconda/envs/dato-env/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [35]:
test_data['diff_sentiment'] = predicted_sentiment - test_data['sentiment']

/Users/April/anaconda/envs/dato-env/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [36]:
acc = np.sum(sum(test_data['diff_sentiment'] == 0))
print acc

31079


In [37]:
total = len(test_data.index)
print total

33336


In [38]:
print round(float(acc)/float(total),2)

0.93


#Learn another classifier with fewer words

In [39]:
significant_words = ['love', 'great', 'easy', 'old', 'little', 'perfect', 'loves', 
      'well', 'able', 'car', 'broke', 'less', 'even', 'waste', 'disappointed', 
      'work', 'product', 'money', 'would', 'return']

In [40]:
vectorizer_word_subset = CountVectorizer(vocabulary=significant_words) # limit to 20 words
train_matrix_word_subset = vectorizer_word_subset.fit_transform(train_data['review_clean'])
test_matrix_word_subset = vectorizer_word_subset.transform(test_data['review_clean'])

#Train a logistic regression model on a subset of data

In [41]:
simple_model = LogisticRegression()

In [42]:
simple_model.fit(train_matrix_word_subset, train_data['sentiment'])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0)

In [43]:
simple_model.coef_.flatten()

array([ 1.36368976,  0.94399959,  1.19253827,  0.08551278,  0.52018576,
        1.50981248,  1.67307389,  0.50376046,  0.19090857,  0.05885467,
       -1.65157634, -0.20956286, -0.51137963, -2.03369861, -2.34829822,
       -0.62116877, -0.32055624, -0.89803074, -0.36216674, -2.10933109])

In [44]:
simple_model_coef_table = pd.DataFrame({'word':significant_words,
                                         'coefficient':simple_model.coef_.flatten()})

In [45]:
simple_model_coef_table.sort('coefficient',ascending = False)

coefficient          word
6      1.673074         loves
5      1.509812       perfect
0      1.363690          love
2      1.192538          easy
1      0.944000         great
4      0.520186        little
7      0.503760          well
8      0.190909          able
3      0.085513           old
9      0.058855           car
11    -0.209563          less
16    -0.320556       product
18    -0.362167         would
12    -0.511380          even
15    -0.621169          work
17    -0.898031         money
10    -1.651576         broke
13    -2.033699         waste
19    -2.109331        return
14    -2.348298  disappointed

In [46]:
sum(simple_model_coef_table['coefficient']>=0)

10

In [47]:
vocab = vectorizer.vocabulary_.keys()

In [48]:
coeffs = {vocab[i]: c for i, c in enumerate(sentiment_model.coef_[0])}

In [49]:
new_dic = {k:v for k, v in coeffs.items() if k in significant_words}

In [50]:
new_table = pd.DataFrame(new_dic.items(), columns=['word', 'new_coeffi'])

In [51]:
new_table_coeff = pd.merge(simple_model_coef_table, new_table, how = 'left', on = 'word' )

In [52]:
new_table_coeff = new_table_coeff[new_table_coeff['coefficient']>=0]

In [53]:
sum(new_table_coeff['new_coeffi'] < 0)


4

In [54]:
new_table_coeff

coefficient     word  new_coeffi
0     1.363690     love    0.206028
1     0.944000    great    0.000011
2     1.192538     easy    0.000135
3     0.085513      old    0.189747
4     0.520186   little   -0.006450
5     1.509812  perfect   -0.011362
6     1.673074    loves    0.124589
7     0.503760     well    0.279507
8     0.190909     able   -0.000080
9     0.058855      car   -0.339657

#Comparing models

In [55]:
predicted_sentiment_train_sentiment = sentiment_model.predict(train_matrix)
train_data['predicted_sentiment_ts'] = predicted_sentiment_train_sentiment
acc_ts = round(float(sum(train_data['predicted_sentiment_ts'] == train_data['sentiment']))/len(train_data.index),2)



/Users/April/anaconda/envs/dato-env/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from IPython.kernel.zmq import kernelapp as app


In [56]:
predicted_simple_train_sentiment = simple_model.predict(train_matrix_word_subset)
train_data['predicted_simple_ts'] = predicted_simple_train_sentiment
acc_tsimple = round(float(sum(train_data['predicted_simple_ts'] == train_data['sentiment']))/len(train_data.index),2)


/Users/April/anaconda/envs/dato-env/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from IPython.kernel.zmq import kernelapp as app


In [57]:
acc_ts > acc_tsimple

True

In [58]:
acc_tsimple

0.87

In [59]:
acc_ts

0.97

compare the accuracy of the sentiment_model and the simple model

In [60]:
predicted_sentiment_test_sentiment = sentiment_model.predict(test_matrix)
test_data['predicted_sentiment_ts'] = predicted_sentiment_test_sentiment
acc_ts_test = round(float(sum(test_data['predicted_sentiment_ts'] == test_data['sentiment']))/len(test_data.index),2)
acc_ts_test

/Users/April/anaconda/envs/dato-env/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from IPython.kernel.zmq import kernelapp as app


0.93

In [61]:
predicted_simple_test_sentiment = simple_model.predict(test_matrix_word_subset)
test_data['predicted_simple_ts'] = predicted_simple_test_sentiment
acc_tsimple_test = round(float(sum(test_data['predicted_simple_ts'] == test_data['sentiment']))/len(test_data.index),2)
acc_tsimple_test

/Users/April/anaconda/envs/dato-env/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from IPython.kernel.zmq import kernelapp as app


0.87

In [62]:
acc_ts_test > acc_tsimple_test

True

# the majority class model

In [63]:
sum(train_data['sentiment'] == 1)

112164

In [64]:
sum(train_data['sentiment'] == -1)

21252

In [65]:
round(float(sum(test_data['sentiment'] ==1))/len(test_data.index),2)

0.84